name: Check and update supported pip

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install GitHub CLI
        uses: actions/gh-cli@v1
        with:
          version: 'latest'

      - name: Run the update script
        run: |
          .github/workflows/update_supported_pip.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
