on:
  push:
    branches:
    - master
    - ci-test
  pull_request:
    branches:
    - master

name: Run Tox tests on Windows

jobs:
  tox_test:
    name: Tox test
    steps:
    - name: Checkout micropipenv
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: python -m pip install tox
    - name: Run Tox tests
      id: test
      run: tox
    
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
